import { APP_URL } from '@/lib/constants';

// Figma 685I9vX5kdlHXAVRcraxvx: 2771:2807, 2771:2740, 2769:2366, 2694:4127.
// Tables and inline styles preserve the design in clients without modern CSS.
const heading = "'Poppins','Segoe UI',Arial,sans-serif";
const body = "'Montserrat','Segoe UI',Arial,sans-serif";
export const escapeEmail = (value: string) => value.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const asset = (name: string) => `${APP_URL}/assets/email/${name}`;
const p = (text: string) => `<p style="margin:24px 0;font:14px/1.5 ${body};color:#232323;">${text}</p>`;
const cta = (text: string, url: string) => `<table role="presentation" align="center" cellpadding="0" cellspacing="0"><tr><td bgcolor="#005ea4" style="border-radius:14px;background-image:linear-gradient(175deg,#005ea4,#006fc2);"><a href="${escapeEmail(url)}" style="display:inline-block;padding:16px 36px;color:white;text-decoration:none;font:500 16px/24px ${heading};">${text}</a></td></tr></table>`;
const logo = `<table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr><td valign="middle" width="24" style="padding:0;line-height:0;"><img src="${asset('mobi-logo.png')}" width="24" height="24" alt="" style="display:block;border:0;background:transparent;"></td><td valign="middle" style="padding:0 0 0 6px;white-space:nowrap;font:500 19px/24px ${heading};">Mobi <span style="font-weight:300">Prop</span></td></tr></table>`;
function shell(label: string, content: string, extraStyles = "", boxed = true) {
  const links = [['Propiedades','/listings'],['Nosotros','/about'],['Blog','/blog'],['Política de privacidad','/privacy-policy'],['Términos y condiciones','/terms-conditions']].map(([t,u])=>`<a href="${APP_URL}${u}" style="color:#e9e9e9;display:inline-block;margin:0 18px 12px 0;text-decoration:none;">${t}</a>`).join('');
  return `<!doctype html><html lang="es-AR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${label} — Mobi Prop</title><style>@media(max-width:480px){.email-header{padding:16px 20px!important;height:auto!important}.email-header td{vertical-align:middle!important}.outer-pad{padding:24px 12px!important}.card-pad{padding:32px 20px!important}.footer-pad{padding:28px 20px!important}} ${extraStyles}</style></head><body style="margin:0;background:${boxed ? '#f0f6fa' : '#fafafa'};"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="${boxed ? 'padding:24px 12px;' : ''}"><table role="presentation" width="600" cellpadding="0" cellspacing="0" style="width:100%;max-width:600px;background:white;${boxed ? 'border:1px solid #dce5ec;border-radius:16px;overflow:hidden;' : ''}"><tr><td class="email-header" style="height:88px;padding:0 40px;background:${boxed ? '#ffffff' : '#fafafa'};border-radius:${boxed ? '16px 16px 0 0' : '0'};border-bottom:1px solid #e9e9e9;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td valign="middle" style="color:#232323;">${logo}</td><td align="right" style="font:12px/17px ${body};color:#232323;">${label}</td></tr></table></td></tr>${content}<tr><td class="footer-pad" bgcolor="#002c4b" style="padding:28px 40px;color:#e9e9e9;background-color:#002c4b;background-image:linear-gradient(rgba(0,44,75,.93),rgba(0,44,75,.93)),url('${APP_URL}/hero/cta-footer-bg.webp');background-position:center;background-size:cover;"><div>${logo.replace('mobi-logo.png','mobi-logo-white-transparent.png')}</div><p style="font:12px/20px ${body};margin:16px 0 18px;">Las Amapolas 455, Buenos Aires<br><a href="tel:+5491180306000" style="color:#e9e9e9;">+54 9 11 8030 6000</a> · <a href="mailto:hola@mobiprop.com.ar" style="color:#e9e9e9;">hola@mobiprop.com.ar</a></p><div style="font:12px/18px ${body};">${links}</div><div style="border-top:1px solid #ffffff26;padding-top:16px;font:11px/18px ${body};">Este correo contiene información sobre tu cuenta, tu consulta o tu visita en Mobi Prop.<br>© ${new Date().getFullYear()} Mobi Prop. Todos los derechos reservados.</div></td></tr></table></td></tr></table></body></html>`;
}
export function card(label: string, title: string, icon: string, content: string, note: string) {
 return shell(label, `<tr><td class="outer-pad" style="padding:40px 28px;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f0f6fa;border:1px solid #e9e9e9;border-radius:20px;"><tr><td align="center" class="card-pad" style="padding:48px 44px 36px;">${icon === "icon-check.png" ? `<table role="presentation" align="center" cellpadding="0" cellspacing="0"><tr><td bgcolor="#005089" width="60" height="60" align="center" valign="middle" style="background:#005089;border-radius:30px;"><img src="${asset(icon)}" width="36" height="36" alt="" style="display:block;border:0;"></td></tr></table>` : `<img src="${asset(icon)}" width="60" height="60" alt="" style="display:block;border:0;background:transparent;">`}<p style="margin:24px 0 4px;font:600 12px/17px ${body};letter-spacing:1px;text-transform:uppercase;color:#005089;">${label}</p><h1 style="margin:0;font:500 28px/42px ${heading};color:#00223a;">${title}</h1>${content}</td></tr><tr><td align="center" style="border-top:1px solid #e9e9e9;padding:24px 32px;font:12px/18px ${body};color:#232323;">${note}</td></tr></table></td></tr>`);
}
export function renderVerificationDesign(params: {code:string;email?:string;confirmationUrl?:string;expiresMinutes?:number}) {
 const url = `${APP_URL}/verify-otp${params.email ? '?email='+(params.email === '{{ .Email }}' ? '{{ .Email | urlquery }}' : encodeURIComponent(params.email))+'&type=signup' : ''}`;
 return card('Verificación de correo','Verificá tu correo electrónico','verify.png',p('¡Gracias por registrarte! Ingresá este código de un solo uso en la página de verificación para activar tu cuenta de Mobi Prop.')+`<div style="margin:24px 0;padding:20px 12px;background:white;border:1px solid #ccdeef;border-radius:12px;font:600 32px/44px ${heading};letter-spacing:8px;color:#005089;">${escapeEmail(params.code)}</div>`+cta('Verificar mi correo',url)+p('Este código se puede usar una sola vez. No lo compartas con nadie.'),"Si no creaste una cuenta en Mobi Prop, podés ignorar este correo.<br>Para activar tu cuenta, necesitás verificar tu correo electrónico.");
}
export function renderResetDesign(params:{url:string;email?:string;expiresMinutes?:number}) {
 return card('Recuperación de contraseña','Restablecé tu contraseña','icon-lock.png',p(`Recibimos una solicitud para restablecer la contraseña de tu cuenta de Mobi Prop${params.email ? ' asociada a <strong style="color:#005089">'+escapeEmail(params.email)+'</strong>' : ''}.`)+cta('Restablecer mi contraseña',params.url)+p("Si no solicitaste este cambio, <strong>podés ignorar este correo</strong>. Tu contraseña no se modificará."),'Por seguridad, este enlace se puede usar una sola vez. Si necesitás ayuda, escribinos a <a href="mailto:hola@mobiprop.com.ar" style="color:#005089">hola@mobiprop.com.ar</a>');
}
export type EmailProperty = {title:string;url:string;image?:string;location:string;price?:string;bedrooms?:number|null;bathrooms?:number|null;area?:number|null};
function propertyCard(property: EmailProperty) {
 const details=[property.bedrooms != null ? `${property.bedrooms} dormitorios` : '',property.bathrooms != null ? `${property.bathrooms} baños` : '',property.area != null ? `${property.area} m²` : ''].filter(Boolean).join(' · ');
 return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:16px 0;border:1px solid #e9e9e9;border-radius:12px;"><tr>${property.image?`<td width="32%"><img src="${escapeEmail(property.image)}" width="175" alt="${escapeEmail(property.title)}" style="display:block;width:100%;max-width:175px;border-radius:12px 0 0 12px;"></td>`:''}<td style="padding:18px;font:12px/20px ${body};color:#4f4f4f;"><strong style="font:500 16px/22px ${heading};color:#232323;">${escapeEmail(property.title)}</strong><br>${escapeEmail(property.location)}<br>${details}<br><span style="color:#0875bd;font-size:16px;">${escapeEmail(property.price??'')}</span><br><a href="${escapeEmail(property.url)}" style="color:#005089;text-decoration:none;">Ver propiedad →</a></td></tr></table>`;
}
export function renderWelcomeDesign(params:{name?:string;ctaUrl?:string;properties?:EmailProperty[]}) {
 const features = [['listing','Propiedades elegidas','Encontrá tu próximo hogar'],['agents','Nuestros agentes','Experiencia en la zona'],['alerts','Tus favoritos','Guardá propiedades']].map(([icon,title,sub])=>`<td width="33%" align="center" style="padding:16px 5px;background:#f0f6fa;border:1px solid #ccdeef;border-radius:12px;"><img src="${asset(icon+'.png')}" width="24" height="24" alt=""><p style="margin:10px 0 2px;font:500 14px/22px ${heading};color:#00223a;">${title}</p><span style="font:12px/20px ${body};">${sub}</span></td>`).join('<td width="8"></td>');
 const recommendations = params.properties?.length ? `<h2 style="margin:40px 0 0;font:500 24px/36px ${heading};color:#00223a;">Recomendadas para vos</h2>${p('Descubrí algunas de nuestras propiedades disponibles.')}${params.properties.map(propertyCard).join('')}${cta('Ver más propiedades',`${APP_URL}/listings`)}` : '';
 return shell('Te damos la bienvenida a Mobi Prop',`<tr><td style="padding:12px 12px 0;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td background="${asset('welcome-hero.jpg')}" height="220" valign="top" style="background:#5c93b2 url('${asset('welcome-hero.jpg')}') center/cover;border-radius:12px;padding:24px;box-sizing:border-box;"><h1 style="font:500 28px/36px ${heading};color:white;margin:0;">Te damos la bienvenida a Mobi Prop${params.name?', '+escapeEmail(params.name):''}!</h1></td></tr></table></td></tr><tr><td class="outer-pad" style="padding:24px 28px 40px;">${p('<strong>Gracias por sumarte a Mobi Prop.</strong> Tu cuenta ya está activa. Explorá nuestras propiedades, contactá a nuestros agentes y encontrá el lugar ideal para vos.')} <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:32px 0 40px;"><tr>${features}</tr></table>${cta('Ver propiedades',params.ctaUrl??`${APP_URL}/listings`)}${recommendations}<div style="margin-top:40px;padding:16px 20px;background:#f0f6fa;border-left:2px solid #005089;border-radius:8px;font:12px/20px ${body};color:#005089;">¿Tenés alguna consulta? Escribinos a <a href="mailto:hola@mobiprop.com.ar">hola@mobiprop.com.ar</a> o al +54 9 11 8030 6000</div></td></tr>`);
}
export function renderVisitDesign(params:{submittedName:string;tourNumber:string;scheduledAtLabel:string;durationLabel:string;propertyTitle?:string|null;propertyLocation?:string|null;agentName?:string|null;confirmationNote?:string|null;ctaUrl:string;requested?:boolean;property?:EmailProperty}) {
 const property=params.property;
 const title=params.requested?'Recibimos tu solicitud de visita':'Tu visita está confirmada';
 const details=[property?.bedrooms != null ? `${property.bedrooms} dormitorios` : '',property?.bathrooms != null ? `${property.bathrooms} baños` : '',property?.area != null ? `${property.area} m²` : ''].filter(Boolean);
 const badges=details.map(text=>`<span style="display:inline-block;margin:8px 8px 0 0;padding:3px 12px;border-radius:20px;background:#e1edf5;color:#005089;font:12px/18px ${body};">${escapeEmail(text)}</span>`).join('');
 const steps=params.requested?['Un agente revisará tu consulta y la disponibilidad de la propiedad',"Te contactaremos por teléfono o WhatsApp para confirmar la visita",'¡Visitá la propiedad!']:['Revisá los detalles de tu visita a continuación','Contactá a tu agente si necesitás cambiar el horario','¡Visitá la propiedad!'];
 const hero=property?.image?`<tr><td style="padding:0;line-height:0;"><img src="${escapeEmail(property.image)}" width="544" alt="${escapeEmail(property.title)}" style="display:block;width:100%;height:auto;border:0;border-radius:16px 16px 0 0;"></td></tr>`:'';
 return shell('Programación de visita', `<tr><td class="outer-pad" style="padding:40px 28px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:white;border:1px solid #e9e9e9;border-radius:16px;">${hero}<tr><td style="padding:24px;">
 <table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td class="tour-summary" valign="top"><h1 style="margin:0;font:500 18px/24px ${heading};color:#00223a;">${escapeEmail(property?.title??params.propertyTitle??'Tu visita a la propiedad')}</h1><p style="margin:4px 0;font:14px/20px ${body};color:#6c6c6c;">${escapeEmail(property?.location??params.propertyLocation??'')}</p>${badges}</td>${property?.price?`<td class="tour-price" nowrap valign="top" align="right" style="white-space:nowrap;padding-left:12px;font:600 16px/27px ${heading};color:#005089;">${escapeEmail(property.price).replace(/ /g, "&nbsp;")}</td>`:''}</tr></table>
 <div style="margin-top:24px;padding:16px 20px;background:#fafcfe;border:1px solid #eef2f6;border-radius:12px;"><p style="margin:0 0 4px;font:500 16px/23px ${heading};color:#232323;">${escapeEmail(params.agentName??'Equipo de Mobi Prop')}</p><p style="margin:0 0 6px;font:12px/18px ${body};color:#6c6c6c;">Tu contacto inmobiliario</p><div style="font:12px/18px ${body};"><a href="tel:+5491180306000" style="color:#232323;text-decoration:none;">+54 9 11 8030 6000</a> · <a href="https://wa.me/5491180306000" style="color:#005089;">WhatsApp</a></div></div>
 <div style="margin-top:13px;padding:20px;background:#f0f6fa;border-radius:12px;"><h2 style="margin:0 0 12px;font:500 14px/21px ${heading};color:#232323;">¿Cómo seguimos?</h2><table role="presentation" width="100%" cellpadding="0" cellspacing="0">${steps.map((text,i)=>`<tr><td width="32" valign="top" style="padding:4px 0;"><span style="display:inline-block;width:22px;border-radius:11px;background:#005089;text-align:center;color:white;font:500 12px/22px ${heading};">${i+1}</span></td><td style="padding:4px 0;color:#4f4f4f;font:14px/20px ${body};">${text}</td></tr>`).join('')}</table></div>
 <h2 style="margin:24px 0 12px;font:500 18px/26px ${heading};color:#00223a;">${title}</h2>${p('Hola '+escapeEmail(params.submittedName)+', '+(params.requested?'estos son los datos de la visita que solicitaste. Nuestro agente todavía debe confirmar la disponibilidad.':'estos son los detalles de tu visita.'))}<p style="font:14px/22px ${body};color:#232323;">${escapeEmail(params.scheduledAtLabel.charAt(0).toLocaleUpperCase("es-AR") + params.scheduledAtLabel.slice(1))}<br>${escapeEmail(params.durationLabel)} · ${escapeEmail(params.tourNumber)}</p>${params.confirmationNote?p(escapeEmail(params.confirmationNote)):''}${cta('Ver mis visitas',params.ctaUrl)}
 </td></tr><tr><td align="center" style="border-top:1px solid #e9e9e9;padding:24px 32px;background:#f0f6fa;border-radius:0 0 16px 16px;font:12px/18px ${body};color:#232323;">¿Preferís hablar por WhatsApp? <a href="https://wa.me/5491180306000" style="color:#005089;">Escribinos al +54 9 11 8030 6000</a></td></tr></table></td></tr>`, '@media(max-width:480px){.tour-summary,.tour-price{display:block!important;width:100%!important;text-align:left!important}.tour-price{padding:12px 0 0!important}}', true);
}
