import { APP_URL } from '@/lib/constants';

// Figma 685I9vX5kdlHXAVRcraxvx: 2771:2807, 2771:2740, 2769:2366, 2694:4127.
// Tables and inline styles preserve the design in clients without modern CSS.
const heading = "'Poppins','Segoe UI',Arial,sans-serif";
const body = "'Montserrat','Segoe UI',Arial,sans-serif";
export const escapeEmail = (value: string) => value.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const asset = (name: string) => `${APP_URL}/assets/email/${name}`;
const p = (text: string) => `<p style="margin:24px 0;font:14px/1.5 ${body};color:#232323;">${text}</p>`;
const cta = (text: string, url: string) => `<table role="presentation" align="center" cellpadding="0" cellspacing="0"><tr><td bgcolor="#005ea4" style="border-radius:14px;background-image:linear-gradient(175deg,#005ea4,#006fc2);"><a href="${escapeEmail(url)}" style="display:inline-block;padding:16px 36px;color:white;text-decoration:none;font:500 16px/24px ${heading};">${text}</a></td></tr></table>`;
const logo = `<img src="${asset('mobi-logo.png')}" width="24" height="24" alt="" style="vertical-align:middle;"> <span style="font:500 19px ${heading};">Mobi <span style="font-weight:300">Prop</span></span>`;
function shell(label: string, content: string) {
  const links = [['Listings','/listings'],['About Us','/about'],['Blog','/blog'],['Privacy Policy','/privacy-policy'],['Terms','/terms-conditions']].map(([t,u])=>`<a href="${APP_URL}${u}" style="color:#e9e9e9;display:inline-block;margin:0 18px 12px 0;text-decoration:none;">${t}</a>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${label} — Mobi Prop</title><style>@media(max-width:480px){.outer-pad{padding:24px 12px!important}.card-pad{padding:32px 20px!important}.footer-pad{padding:28px 20px!important}} </style></head><body style="margin:0;background:#fafafa;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table role="presentation" width="600" cellpadding="0" cellspacing="0" style="width:100%;max-width:600px;background:white;"><tr><td style="height:88px;padding:0 40px;background:#fafafa;border-bottom:1px solid #e9e9e9;"><table role="presentation" width="100%"><tr><td style="color:#232323;">${logo}</td><td align="right" style="font:12px/17px ${body};color:#232323;">${label}</td></tr></table></td></tr>${content}<tr><td class="footer-pad" bgcolor="#002c4b" style="padding:28px 40px;color:#e9e9e9;background-color:#002c4b;background-image:linear-gradient(rgba(0,44,75,.93),rgba(0,44,75,.93)),url('${APP_URL}/hero/cta-footer-bg.webp');background-position:center;background-size:cover;"><div>${logo}</div><p style="font:12px/20px ${body};margin:16px 0 18px;">Las Amapolas 455, Buenos Aires<br><a href="tel:+5491180306000" style="color:#e9e9e9;">+54 9 11 8030 6000</a> · <a href="mailto:hola@mobiprop.com.ar" style="color:#e9e9e9;">hola@mobiprop.com.ar</a></p><div style="font:12px/18px ${body};">${links}</div><div style="border-top:1px solid #ffffff26;padding-top:16px;font:11px/18px ${body};">This is a transactional email about your Mobi Prop account or visit.<br>© ${new Date().getFullYear()} Mobi Prop. All rights reserved.</div></td></tr></table></td></tr></table></body></html>`;
}
function card(label: string, title: string, icon: string, content: string, note: string) {
 return shell(label, `<tr><td class="outer-pad" style="padding:40px 28px;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f0f6fa;border:1px solid #e9e9e9;border-radius:20px;"><tr><td align="center" class="card-pad" style="padding:48px 44px 36px;"><img src="${asset(icon)}" width="60" height="60" alt="" style="display:block;"><p style="margin:24px 0 4px;font:600 12px/17px ${body};letter-spacing:1px;text-transform:uppercase;color:#005089;">${label}</p><h1 style="margin:0;font:500 28px/42px ${heading};color:#00223a;">${title}</h1>${content}</td></tr><tr><td align="center" style="border-top:1px solid #e9e9e9;padding:24px 32px;font:12px/18px ${body};color:#232323;">${note}</td></tr></table></td></tr>`);
}
export function renderVerificationDesign(params: {code:string;email?:string;confirmationUrl?:string;expiresMinutes?:number}) {
 const url = `${APP_URL}/verify-otp${params.email ? '?email='+(params.email === '{{ .Email }}' ? '{{ .Email | urlquery }}' : encodeURIComponent(params.email))+'&type=signup' : ''}`;
 return card('Email Verification','Verify your email address','verify.png',p('Thanks for signing up! Enter this one-time code on the verification page to activate your Mobi Prop account.')+`<div style="margin:24px 0;padding:20px 12px;background:white;border:1px solid #ccdeef;border-radius:12px;font:600 32px/44px ${heading};letter-spacing:8px;color:#005089;">${escapeEmail(params.code)}</div>`+cta('Verify Email Address',url)+p('This code can only be used once. Do not share it with anyone.'),"If you didn't create a Mobi Prop account, you can safely ignore this email.<br>Your account requires email verification.");
}
export function renderResetDesign(params:{url:string;email?:string;expiresMinutes?:number}) {
 return card('Password Reset','Reset your password','reset.png',p(`We received a request to reset the password for your Mobi Prop account${params.email ? ' associated with <strong style="color:#005089">'+escapeEmail(params.email)+'</strong>' : ''}.`)+cta('Reset My Password',params.url)+p("If you didn't request this, <strong>you can safely ignore this email</strong>. Your password will not change."),'For security, this link can only be used once. If you need help, contact us at <a href="mailto:hola@mobiprop.com.ar" style="color:#005089">hola@mobiprop.com.ar</a>');
}
export type EmailProperty = {title:string;url:string;image?:string;location:string;price?:string;bedrooms?:number|null;bathrooms?:number|null;area?:number|null};
function propertyCard(property: EmailProperty) {
 const details=[property.bedrooms != null ? `${property.bedrooms} Bedrooms` : '',property.bathrooms != null ? `${property.bathrooms} Bathrooms` : '',property.area != null ? `${property.area} m²` : ''].filter(Boolean).join(' · ');
 return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:16px 0;border:1px solid #e9e9e9;border-radius:12px;"><tr>${property.image?`<td width="32%"><img src="${escapeEmail(property.image)}" width="175" alt="${escapeEmail(property.title)}" style="display:block;width:100%;max-width:175px;border-radius:12px 0 0 12px;"></td>`:''}<td style="padding:18px;font:12px/20px ${body};color:#4f4f4f;"><strong style="font:500 16px/22px ${heading};color:#232323;">${escapeEmail(property.title)}</strong><br>${escapeEmail(property.location)}<br>${details}<br><span style="color:#0875bd;font-size:16px;">${escapeEmail(property.price??'')}</span><br><a href="${escapeEmail(property.url)}" style="color:#005089;text-decoration:none;">View property →</a></td></tr></table>`;
}
export function renderWelcomeDesign(params:{name?:string;ctaUrl?:string;properties?:EmailProperty[]}) {
 const features = [['listing','Curated Listings','Find your next home'],['agents','Our Agents','Local expertise'],['alerts','Your Favourites','Save properties']].map(([icon,title,sub])=>`<td width="33%" align="center" style="padding:16px 5px;background:#f0f6fa;border:1px solid #ccdeef;border-radius:12px;"><img src="${asset(icon+'.png')}" width="24" height="24" alt=""><p style="margin:10px 0 2px;font:500 14px/22px ${heading};color:#00223a;">${title}</p><span style="font:12px/20px ${body};">${sub}</span></td>`).join('<td width="8"></td>');
 const recommendations = params.properties?.length ? `<h2 style="margin:40px 0 0;font:500 24px/36px ${heading};color:#00223a;">Recommended for you</h2>${p('Explore a few of our current properties.')}${params.properties.map(propertyCard).join('')}${cta('Explore More Properties',`${APP_URL}/listings`)}` : '';
 return shell('Welcome to Mobi Prop',`<tr><td style="padding:12px 12px 0;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td background="${asset('welcome-hero.jpg')}" height="220" valign="top" style="background:#5c93b2 url('${asset('welcome-hero.jpg')}') center/cover;border-radius:12px;padding:24px;box-sizing:border-box;"><h1 style="font:500 28px/36px ${heading};color:white;margin:0;">Welcome to Mobi Prop${params.name?', '+escapeEmail(params.name):''}!</h1></td></tr></table></td></tr><tr><td class="outer-pad" style="padding:24px 28px 40px;">${p('<strong>Thank you for joining Mobi Prop.</strong> Your account is now active and ready to use. Start exploring curated listings, connect with our agents, and find your perfect property.')} <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:32px 0 40px;"><tr>${features}</tr></table>${cta('Browse Properties',params.ctaUrl??`${APP_URL}/listings`)}${recommendations}<div style="margin-top:40px;padding:16px 20px;background:#f0f6fa;border-left:2px solid #005089;border-radius:8px;font:12px/20px ${body};color:#005089;">Questions? Reach us at <a href="mailto:hola@mobiprop.com.ar">hola@mobiprop.com.ar</a> or +54 9 11 8030 6000</div></td></tr>`);
}
export function renderVisitDesign(params:{submittedName:string;tourNumber:string;scheduledAtLabel:string;durationLabel:string;propertyTitle?:string|null;propertyLocation?:string|null;agentName?:string|null;confirmationNote?:string|null;ctaUrl:string;requested?:boolean;property?:EmailProperty}) {
 const property=params.property;
 const title=params.requested?'Your visit request has been received':'Your visit is confirmed';
 const details=[property?.bedrooms != null ? `${property.bedrooms} Bedrooms` : '',property?.bathrooms != null ? `${property.bathrooms} Bathrooms` : '',property?.area != null ? `${property.area} m²` : ''].filter(Boolean);
 const badges=details.map(text=>`<span style="display:inline-block;margin:8px 8px 0 0;padding:3px 12px;border-radius:20px;background:#e1edf5;color:#005089;font:12px/18px ${body};">${escapeEmail(text)}</span>`).join('');
 const steps=params.requested?['Agent reviews your inquiry and property availability',"You'll receive a call or WhatsApp message to confirm the appointment",'Visit the property!']:['Review your appointment details below','Contact your agent if you need to change the time','Visit the property!'];
 const hero=property?.image?`<tr><td background="${escapeEmail(property.image)}" height="300" valign="top" style="height:300px;background:#5c93b2 url('${escapeEmail(property.image)}') center/cover;border-radius:16px 16px 0 0;"><div style="padding:20px;color:white;"><img src="${asset('mobi-logo-white.png')}" width="24" height="24" alt="" style="vertical-align:middle;"> <span style="font:500 18px/24px ${heading};">Mobi <span style="font-weight:300">Prop</span></span></div></td></tr>`:`<tr><td style="padding:20px;color:#232323;">${logo}</td></tr>`;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} — Mobi Prop</title></head><body style="margin:0;background:#f0f6fa;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table role="presentation" width="640" cellpadding="0" cellspacing="0" style="width:100%;max-width:640px;background:#f1f5f9;"><tr><td style="padding:32px 20px 24px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:white;border-radius:16px;box-shadow:0 4px 24px #00223a14;">${hero}<tr><td style="padding:24px;">
 <table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr><td valign="top"><h1 style="margin:0;font:500 18px/24px ${heading};color:#00223a;">${escapeEmail(property?.title??params.propertyTitle??'Your property visit')}</h1><p style="margin:4px 0;font:14px/20px ${body};color:#6c6c6c;">${escapeEmail(property?.location??params.propertyLocation??'')}</p>${badges}</td>${property?.price?`<td valign="top" align="right" style="padding-left:12px;font:600 16px/27px ${heading};color:#005089;">${escapeEmail(property.price)}</td>`:''}</tr></table>
 <div style="margin-top:24px;padding:16px 20px;background:#fafcfe;border:1px solid #eef2f6;border-radius:12px;"><p style="margin:0 0 4px;font:500 16px/23px ${heading};color:#232323;">${escapeEmail(params.agentName??'Mobi Prop Team')}</p><p style="margin:0 0 6px;font:12px/18px ${body};color:#6c6c6c;">Your real estate contact</p><div style="font:12px/18px ${body};"><a href="tel:+5491180306000" style="color:#232323;text-decoration:none;">+54 9 11 8030 6000</a> · <a href="https://wa.me/5491180306000" style="color:#005089;">WhatsApp</a></div></div>
 <div style="margin-top:13px;padding:20px;background:#f0f6fa;border-radius:12px;"><h2 style="margin:0 0 12px;font:500 14px/21px ${heading};color:#232323;">What happens next?</h2><table role="presentation" width="100%" cellpadding="0" cellspacing="0">${steps.map((text,i)=>`<tr><td width="32" valign="top" style="padding:4px 0;"><span style="display:inline-block;width:22px;border-radius:11px;background:#005089;text-align:center;color:white;font:500 12px/22px ${heading};">${i+1}</span></td><td style="padding:4px 0;color:#4f4f4f;font:14px/20px ${body};">${text}</td></tr>`).join('')}</table></div>
 <h2 style="margin:24px 0 12px;font:500 18px/26px ${heading};color:#00223a;">${title}</h2>${p('Hello '+escapeEmail(params.submittedName)+', '+(params.requested?'your preferred appointment is shown below. Our agent still needs to confirm availability.':'your appointment details are shown below.'))}<p style="font:14px/22px ${body};color:#232323;">${escapeEmail(params.scheduledAtLabel)}<br>${escapeEmail(params.durationLabel)} · ${escapeEmail(params.tourNumber)}</p>${params.confirmationNote?p(escapeEmail(params.confirmationNote)):''}${cta('View My Visits',params.ctaUrl)}
 </td></tr></table></td></tr><tr><td align="center" style="padding:0 20px 32px;font:12px/19px ${body};color:#6c6c6c;">© ${new Date().getFullYear()} Mobi Prop · Las Amapolas 455, Buenos Aires<br><a href="${APP_URL}/privacy-policy" style="color:#005089;">Privacy Policy</a> · <a href="${APP_URL}/terms-conditions" style="color:#005089;">Terms of Service</a></td></tr></table></td></tr></table></body></html>`;
}
