// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

config({ path: ".env" });
config({ path: ".env.local", override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI commands (migrate, db push, studio) need a direct (non-pgbouncer) connection.
    // The app runtime keeps using DATABASE_URL (pooled) via src/lib/prisma.ts.
    url: process.env["DIRECT_URL"],
  },
});
